# // Makefile git add commit push github All in One command: https://panjeh.medium.com/makefile-git-add-commit-push-github-all-in-one-command-9dcf76220f49

git:
	git add .
	git commit -m "$m"
	git push 
